
samples_name: 
    AGEJ8XXXX_1_11:g:ApekiN1
samples_unit:
    [1,2]

vcf_gatk_name:
    call_gatk

vcf_bayes_name:
    call_bayes

vcf_deepvariant_name: 
    call_deepvariant
genome_name: GCA_904849725.1_MorexV3_pseudomolecules.chrnames.fna
