

samples_name: 
    C3FGNACXX_1_15
samples_unit:
    [1,2]

working_directory: 
/home/iveron/barley-variant-calling/

vcf_gatk_name:
    call_gatk

vcf_bayes_name:
    call_bayes

vcf_deepvariant_name: 
    call_deepvariant
genome_name: GCA_904849725.1_MorexV3_pseudomolecules.chrnames.fna
